_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 5
                - 8
                - 28
                - 49
                - 53
                - 55
                - 105
            "2":
                - 5
                - 8
                - 28
                - 49
                - 53
                - 55
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
dataset:
    value: Diabetes dataset
metric:
    value: Acurácia
model:
    value: diabetes_model
